### ISSUE TITLE
Project: NEON-Niwot SDMs forest species

### ISSUE THREAD

**Issue by brettmelbourne** [EBIO6100Spring2020/Data-sandbox#4]
Species distribution models of forest species

**Comment by annaspiers** [comment]
I'm interested

**Comment by mech3132** [comment]
Si

**Comment by cltorrens** [comment]
interested

**Comment by gottacatchenall** [comment]
interested

**Comment by scelmendorf** [comment]
Adding some relevant datasets/papers to this one:
Veblen dataset - https://doi.org/10.6073/pasta/662c9312de7ff8365543b496b754e9fe. 
Recent paper using the Veblen dataset: https://doi.org/10.1139/cjfr-2019-0023

neon tree data - mapped stems etc described here:
http://data.neonscience.org/documents/10179/1723439/NEON.DOC.000914vA/b21f8a50-2f1e-4261-8890-3f922fd78141

and the general diversity protocol - which presumably has plots both in the forest and tundra at neon described here: https://doi.org/10.1002/ecs2.2603

**Comment by grantvagle** [comment]
Interested

**Comment by mbjoseph** [comment]
Good paper on the ground beetle sampling design (with some ideas for projects toward the end): 

Hoekman, David, Katherine E. LeVan, George E. Ball, Robert A. Browne, Robert L. Davidson, Terry L. Erwin, C. Barry Knisley et al. "Design for ground beetle abundance and diversity sampling within the National Ecological Observatory Network." Ecosphere 8, no. 4 (2017): e01744.
https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.1744

**Comment by mbjoseph** [comment]
# EDA tasks for 2020-02-06

- [x] Find discrepancies in parataxonomist and expert taxonomist species IDs
- [ ] Map spatial location of samples on a DEM

###  Start visualizing some of the predictor variables

- [ ] DP3.30025.001 slope/aspect 
- [ ] DP3.30024.001 elevation (digital terrain model)
- [ ] DP1.00006.001 precipitation
- [ ] DP1.00098.001 relative humidity
- [ ] DP1.00005.001 IR biological temp
- [ ] DP1.00014.001 Shortwave radiation (direct and diffuse pyranometer)
- [ ] DP1.00023.001 Shortwave and longwave radiation (net radiometer)
- [ ] DP2.30012.001 LAI - spectrometer - flightline
- [ ] DP3.30012.001 LAI mosaic (ran into an [issue](https://github.com/NEONScience/NEON-utilities/issues/75) here)
- [ ] DP1.00041.001 soil temp
- [x] DP1.00094.001 [Soil water content and water salinity](https://github.com/EBIO6100Spring2020/Data-sandbox/blob/master/niwot-soil-water-content.R)
- [ ] DP1.00041.001 soil temp
- [ ] DP1.10098.001 Woody plant vegetation structure
- [ ] DP1.10033.001 Litterfall and fine woody debris sampling

**Comment by scelmendorf** [comment]
Also relevant - if you haven't already worked this out most of the 'OS' products (e.g. stuff that is not sensors or aop) come with a user guide that gives a brief description of the parent-child relationships (subsetting), spatial and temporal frequency. 
http://data.neonscience.org/api/v0/documents/NEON_beetle_userGuide_vA
I think it should also come with your data if you pick the 'expanded' option rather than 'basic' in your download.

**Comment by mbjoseph** [comment]
Also relevant (and gets back to the mulitnomial observation model that @scelmendorf mentioned) is this recent paper, which provides a modeling framework for multispecies data under misclassification error that explicitly separates the presence/absence of each species, the activity level (expected count, given presence) of each species, and species misclassification probabiliites: https://doi.org/10.1111/2041-210X.13315

We could also probably think of some simpler quick and dirty approaches (e.g., focus on species that the parataxonomists can reliably identify).

**Comment by mbjoseph** [comment]
Linking out to the [MEE paper](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13858) @annaspiers wrote on this stuff 🎉 🥳
